export const disclaimerBoundaryFields=["decision_domain","urgency_or_deadline","jurisdiction_date_eligibility","result_evidence_state","official_or_registered_handoff","system_and_service_state","rights_support_data_state","reliance_decision","next_action"] as const;
export type DecisionDomain="general"|"legal"|"tax"|"migration"|"employment"|"financial"|"health"|"emergency"|"paid_product"|"privacy_incident"|"content_error";
export type BoundaryUrgency="unknown"|"nonurgent"|"today"|"fixed_deadline"|"immediate_danger";
export type DisclaimerBoundary={decision_domain:DecisionDomain;urgency_or_deadline:BoundaryUrgency;jurisdiction_date_eligibility:{jurisdiction:string;checked_on:string;version:string;eligibility:string};result_evidence_state:string;official_or_registered_handoff:string;system_and_service_state:{source_status:string;ai_or_automation:string;human_owner:string;error_or_outage:string};rights_support_data_state:{acl_non_exclusion:string;paid_support_or_refund:string;data_location_or_incident:string};reliance_decision:"continue_to_verify"|"hold"|"stop_now"|"contact_now"|"do_not_rely";next_action:"call_000"|"open_primary_official_source"|"verify_registered_professional"|"verify_jurisdiction_date_eligibility"|"compare_original_evidence"|"preserve_local_record_then_use_support"|"report_privacy_incident"|"report_content_error"};
export type BoundaryInput={domain?:DecisionDomain;urgency?:BoundaryUrgency;sourceStatus?:"current"|"recheck"|"stale"|"broken"|"unknown";evidence?:string;jurisdiction?:string;version?:string;eligibility?:string;immediateDanger?:boolean};
const unknownRights={acl_non_exclusion:"unknown",paid_support_or_refund:"unknown",data_location_or_incident:"unknown"};
export function deriveDisclaimerBoundary(input:BoundaryInput={}):DisclaimerBoundary{
 const danger=input.immediateDanger||input.domain==="emergency"||input.urgency==="immediate_danger";if(danger)return{decision_domain:"emergency",urgency_or_deadline:"immediate_danger",jurisdiction_date_eligibility:{jurisdiction:"Australia",checked_on:"2026-09-07",version:"unknown",eligibility:"general"},result_evidence_state:"unknown",official_or_registered_handoff:"triple_zero",system_and_service_state:{source_status:"recheck",ai_or_automation:"unknown",human_owner:"public emergency owner",error_or_outage:"unknown"},rights_support_data_state:{acl_non_exclusion:"not_applicable",paid_support_or_refund:"not_applicable",data_location_or_incident:"not_applicable"},reliance_decision:"stop_now",next_action:"call_000"};
 const domain=input.domain??"general",urgency=input.urgency??"unknown",source=input.sourceStatus??"recheck";const boundary={jurisdiction:input.jurisdiction??"unknown",checked_on:"2026-09-07",version:input.version??"unknown",eligibility:input.eligibility??"unknown"};
 let handoff="unknown",reliance:DisclaimerBoundary["reliance_decision"]="hold",next:DisclaimerBoundary["next_action"]="open_primary_official_source";const owner="human owner unknown";let rights={...unknownRights,acl_non_exclusion:"applicable:/terms"};
 if(domain==="legal"){handoff=urgency==="nonurgent"?"police_assistance_line":"legal_aid_clc_or_lawyer";reliance="contact_now";next=urgency==="fixed_deadline"?"verify_registered_professional":"open_primary_official_source";}
 else if(domain==="health"){handoff=urgency==="today"?"lifeline_crisis_support":"healthdirect_or_clinician";reliance=urgency==="unknown"?"hold":"contact_now";rights.data_location_or_incident="applicable:/privacy";}
 else if(domain==="tax"){handoff="ato_or_tpb_agent";next="verify_jurisdiction_date_eligibility";}
 else if(domain==="migration"){handoff="home_affairs_authorised_help";reliance=urgency==="fixed_deadline"?"contact_now":"hold";next=urgency==="fixed_deadline"?"verify_registered_professional":"verify_jurisdiction_date_eligibility";}
 else if(domain==="employment"){handoff="fair_work_or_relevant_regulator";reliance="contact_now";}
 else if(domain==="financial"){handoff="bank_or_national_debt_helpline";reliance="contact_now";}
 else if(domain==="paid_product"){handoff="hoju_product_support";next="preserve_local_record_then_use_support";rights={acl_non_exclusion:"applicable:/terms",paid_support_or_refund:"applicable:/payment-help",data_location_or_incident:"applicable:/data-transfer"};}
 else if(domain==="privacy_incident"){handoff="privacy_then_oaic";reliance="contact_now";next="report_privacy_incident";rights.data_location_or_incident="applicable:/privacy#retention-delete";}
 else if(domain==="content_error"){handoff="content_correction";reliance="do_not_rely";next="report_content_error";}
 if(source==="stale"||source==="broken"||source==="unknown"){reliance=domain==="content_error"?"do_not_rely":"hold";if(!["paid_product","privacy_incident","content_error"].includes(domain))next="open_primary_official_source";}
 return{decision_domain:domain,urgency_or_deadline:urgency,jurisdiction_date_eligibility:boundary,result_evidence_state:input.evidence??"unknown",official_or_registered_handoff:handoff,system_and_service_state:{source_status:source,ai_or_automation:"unknown",human_owner:owner,error_or_outage:"unknown"},rights_support_data_state:rights,reliance_decision:reliance,next_action:next};
}
