import Link from "next/link";import {Header} from "@/components/layout/Header";import {Footer} from "@/components/layout/Footer";import {Container} from "@/components/ui/Container";import {LocalProjectChecklist,type ProjectGroup} from "@/components/tools/LocalProjectChecklist";import {DaspReadinessCheck} from "@/components/tools/DaspReadinessCheck";import {BreadcrumbJsonLd} from "@/components/seo/JsonLd";import {createPageMetadata} from "@/lib/site";

export const metadata=createPageMetadata({title:"호주 귀국 준비 체크리스트와 Super DASP 안내 | Hoju Compass",description:"호주 생활을 마치기 전 퇴사, 렌트, 공과금, 세금과 계정 준비부터 출국 후 Super DASP 신청까지 단계별로 확인하세요.",path:"/leaving-australia-guide"});
const departureGroups:ProjectGroup[]=[
 {title:"4–8주 전",items:[{id:"visa-plan",label:"비자 상태와 출국 계획 확인",detail:"출국이 현재 비자와 향후 신청에 미치는 영향이 있다면 공식 안내나 등록 전문가에게 확인하세요."},{id:"notice-work",label:"퇴사 통지와 마지막 근무일 합의",detail:"계약상 통지 기간, 최종 급여일과 미사용 휴가 처리를 서면 확인하세요."},{id:"notice-home",label:"렌트 퇴거 통지",detail:"계약 형태와 주·준주 규정에 맞는 통지, 청소·키 반납·Inspection 일정을 잡으세요."},{id:"flight",label:"항공·수하물·보험 확인",detail:"취소 조건, 추가 수하물과 출국일까지의 보험 보장을 확인하세요."}]},
 {title:"돈·세금·Super",items:[{id:"final-pay",label:"최종 급여와 Payslip 확인",detail:"급여, 수당, 휴가와 마지막 Super 납입 시점을 확인하세요."},{id:"income",label:"Income statement와 세금 기록 확보",detail:"myGov·ATO 접근을 확인하고 필요한 Payslip과 영수증을 안전하게 보관하세요."},{id:"super-details",label:"모든 Super 계정 정보 저장",detail:"펀드명, ABN, 회원번호와 연락처를 안전한 개인 기록에 보관하세요."},{id:"bank",label:"은행 계좌 유지·해지 순서 결정",detail:"보증금, 최종 급여, 세금 또는 DASP 수령 전에 계좌를 닫지 않도록 지급 방법을 확인하세요."},{id:"tax-plan",label:"마지막 Tax return 일정 확인",detail:"출국이 신고 의무와 세법상 거주 상태에 미치는 영향은 ATO 또는 등록 세무사에게 확인하세요."}]},
 {title:"집·서비스·차량",items:[{id:"condition",label:"Condition report와 퇴거 사진",detail:"모든 방, 가전, 계량기와 기존 손상을 날짜와 함께 기록하세요."},{id:"bond",label:"Bond 반환 절차 시작",detail:"관할 지역 공식 시스템에서 청구 상태와 이의제기 기한을 확인하세요."},{id:"utilities",label:"전기·가스·인터넷 종료",detail:"최종 검침, 해지일, 장비 반납과 마지막 청구 주소를 확인하세요."},{id:"phone",label:"호주 전화번호와 2단계 인증 계획",detail:"번호 해지 전에 은행·myGov·이메일 등의 로그인·복구 수단을 점검하세요."},{id:"vehicle",label:"차량 판매·이전·Rego 처리",detail:"등록 주의 공식 이전 절차, 보험 종료와 통행료 계정을 확인하세요."},{id:"mail",label:"우편·배송 주소 정리",detail:"중요 기관의 연락처를 직접 변경하고 자동 배송을 중지하세요."}]},
 {title:"출국 직전·출국 후",items:[{id:"keys",label:"열쇠·장비 반납 증빙",detail:"열쇠, 리모컨, 인터넷 장비와 작업 장비의 반납 기록을 받으세요."},{id:"access",label:"해외에서 계정 로그인 시험",detail:"myGov, ATO, Super, 은행의 안전한 로그인과 복구 방법을 확인하세요."},{id:"visa-ceased",label:"출국 후 모든 임시비자 종료 여부 확인",detail:"DASP는 출국했고 보유한 모든 임시비자가 더 이상 유효하지 않을 때 제출할 수 있습니다."},{id:"dasp",label:"DASP 공식 온라인 신청",detail:"ATO 시스템에서 펀드 또는 ATO가 보유한 Super를 확인하고 신청하세요."},{id:"follow-up",label:"최종 정산 추적",detail:"Bond, 급여, 세금, 공과금과 DASP 지급 내역을 확인하고 기록을 보관하세요."}]},
];
export default function LeavingAustraliaGuidePage(){return <><BreadcrumbJsonLd items={[{name:"홈",path:"/"},{name:"호주 귀국 준비",path:"/leaving-australia-guide"}]}/><Header/><main className="py-12 sm:py-16"><Container><Link href="/tools" className="inline-flex min-h-11 items-center text-sm font-medium text-muted hover:text-navy">&larr; 도구 목록으로 돌아가기</Link><div className="mt-5 max-w-4xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-gold">호주 생활 마무리</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-navy sm:text-4xl">귀국 준비부터 Super DASP 신청까지</h1><p className="mt-4 text-base leading-7 text-muted sm:text-lg">호주를 떠나기 전에 퇴사, 집, 공과금, 은행과 계정 접근을 정리하고, 출국 후에는 비자 종료를 확인한 뒤 DASP와 마지막 세금 업무를 진행하세요.</p></div>
<nav className="mt-6 flex flex-wrap gap-2" aria-label="귀국 준비 페이지 바로가기"><a href="#departure-prep" className="inline-flex min-h-11 items-center rounded-full border border-border bg-white px-4 text-sm font-semibold text-navy">출국 전 준비</a><a href="#dasp-conditions" className="inline-flex min-h-11 items-center rounded-full border border-border bg-white px-4 text-sm font-semibold text-navy">DASP 조건</a><a href="#dasp-after-submit" className="inline-flex min-h-11 items-center rounded-full border border-border bg-white px-4 text-sm font-semibold text-navy">신청 뒤 확인</a></nav>
<section className="my-8 grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-gold/40 bg-gold/5 p-5"><p className="text-sm font-semibold text-gold">출국 전</p><h2 className="mt-2 font-semibold text-navy">정보와 접근권 확보</h2><p className="mt-2 text-sm leading-6 text-muted">Super·세금·은행·렌트 정보를 확보하고 해외에서도 로그인 가능한지 확인하세요.</p></article><article className="rounded-2xl border border-border bg-white p-5"><p className="text-sm font-semibold text-gold">출국 후</p><h2 className="mt-2 font-semibold text-navy">모든 임시비자 종료 뒤 DASP</h2><p className="mt-2 text-sm leading-6 text-muted">DASP는 호주를 떠났고 보유한 모든 임시비자가 더 이상 유효하지 않을 때 제출할 수 있습니다.</p></article><article className="rounded-2xl border border-border bg-white p-5"><p className="text-sm font-semibold text-gold">6개월 이후</p><h2 className="mt-2 font-semibold text-navy">ATO 보유 Super 확인</h2><p className="mt-2 text-sm leading-6 text-muted">미청구 금액이 펀드에서 ATO로 이전될 수 있지만 이후에도 공식 시스템에서 청구할 수 있습니다.</p></article></section>
<div id="departure-prep" className="scroll-mt-24"><LocalProjectChecklist storageKey="leaving-australia-project" eyebrow="출국 전후 20개 준비 항목" title="귀국 준비 프로젝트" description="체크 상태와 출국 예정일만 이 브라우저에 저장합니다. TFN, 여권번호, 회원번호와 은행정보는 입력하지 마세요." groups={departureGroups} dateLabel="출국 예정일" calendarTitle="호주 출국 전 최종 점검"/></div>
<section className="mt-8 border border-navy/20 bg-white p-5 sm:p-6" aria-labelledby="leaving-pro-cta"><div className="grid gap-5 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-gold">Leaving Australia Pack Pro</p><h2 id="leaving-pro-cta" className="mt-2 text-xl font-semibold text-navy">출국 뒤 남은 정산까지 한곳에서 추적하세요.</h2><p className="mt-2 text-sm leading-6 text-muted">무료 체크리스트로 출국 순서를 챙기고, 정산 기록을 더 자세히 남기려면 Bond·마지막 급여·DASP의 질문, 연락처와 결과 메모를 한곳에 정리할 수 있어요. 제품 페이지에서 제공 범위와 현재 구매 조건을 확인하세요.</p><p className="mt-2 text-xs leading-5 text-muted">ATO DASP 온라인 신청은 공식 무료 경로이며 Pro 구매는 신청 조건이 아닙니다. Home Affairs Form 1194는 신원·이민 상태 증명을 위한 별도 양식으로, 모든 온라인 신청자가 유료 증명서를 사야 한다는 뜻이 아닙니다.</p></div><Link href="/leaving-australia-pro" className="inline-flex min-h-12 items-center justify-center bg-navy px-5 text-sm font-semibold text-white">정산 기록 기능·구매 조건 보기 →</Link></div></section>
<section className="mt-8 rounded-2xl border border-border bg-white p-5 sm:p-8" aria-labelledby="departure-follow-up-heading">
  <h2 id="departure-follow-up-heading" className="text-2xl font-semibold text-navy">한국에 도착한 뒤, 이 표에 답할 수 있으면 덜 막막해요</h2>
  <div className="mt-5 overflow-x-auto rounded-xl border border-border" role="region" aria-label="출국 전후 정산 확인 표" tabIndex={0}>
    <table className="w-full min-w-[32rem] text-left text-sm leading-6"><thead className="bg-surface text-navy"><tr>{["남은 일", "출국 전 남길 것", "출국 후 완료 확인"].map((heading) => <th key={heading} scope="col" className="p-4">{heading}</th>)}</tr></thead><tbody>{[["Bond", "공식 접수 경로, 청구·분쟁 상태, 사진·열쇠반납 기록", "처리결과와 실제 수령액 대조"], ["마지막 급여", "근무기록·Payslip, 추가 지급 예정일, Payroll 연락처", "수정 명세서와 추가 입금 확인"], ["전기·인터넷", "서비스 종료일, 최종검침, 장비반납 기록", "마지막 청구기간·Credit/잔액 확인"], ["세금·Super", "안전한 계정접근 방법, 자료 보관 위치, 미확인 납입", "공식 자격·신고/신청 결과와 지급명세 대조"]].map(([item, before, after]) => <tr key={item} className="border-t border-border"><th scope="row" className="p-4 align-top text-navy">{item}</th><td className="p-4 align-top text-muted">{before}</td><td className="p-4 align-top text-muted">{after}</td></tr>)}</tbody></table>
  </div>
  <p className="mt-5 text-sm leading-7 text-muted">각 줄에는 ‘완료/미완료’만 쓰기보다 마지막 연락일·상대의 답·다음에 물을 질문을 적으세요. ‘환급 예정’과 ‘입금 확인’은 다릅니다. 정확한 금액을 모르면 0으로 적지 말고 확인 필요로 남기세요. 메모하는 날짜는 개인 확인 일정이고 법정 신청기한을 대신하지 않습니다.</p>
  <p className="mt-4 text-sm leading-7 text-muted">가상 예시: 인터넷 장비를 반납했고 회사가 수령했다고 답했지만 마지막 청구서는 아직 오지 않았습니다. 이 경우 장비반납은 완료, 최종정산은 확인 대기로 나눕니다. 아래 문장으로 최종 서비스 종료일·잔액 또는 Credit·최종 청구서 예정일을 물어볼 수 있습니다.</p>
  <blockquote className="mt-4 break-words border-l-4 border-gold bg-surface p-5 text-sm leading-7 text-navy" lang="en">Please confirm the final service date, any remaining balance or credit, and when I will receive the final bill.</blockquote>
</section>
<section className="mt-10 rounded-3xl bg-navy p-6 text-white sm:p-8" aria-labelledby="dasp-heading"><p className="text-sm font-semibold text-gold">Departing Australia Superannuation Payment</p><h2 id="dasp-heading" className="mt-2 text-3xl font-semibold">DASP는 ‘전액 환급’이 아닙니다</h2><p className="mt-3 max-w-4xl text-sm leading-7 text-white/70">대상이 되는 전 임시거주자가 출국 후 Super를 받는 제도이며 지급 전에 세금이 원천징수됩니다. ATO는 Working Holiday Maker의 DASP 과세 대상 부분에 65% 세율이 적용된다고 안내합니다. 실제 지급액은 계정의 tax-free·taxed·untaxed 구성과 비자 이력에 따라 달라집니다.</p><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-xl border border-white/15 p-4"><strong className="text-gold">WHM taxable component</strong><span className="mt-2 block text-2xl font-semibold">65%</span><span className="mt-1 block text-xs text-white/60">ATO가 안내하는 원천징수율</span></div><div className="rounded-xl border border-white/15 p-4"><strong className="text-gold">Tax-free component</strong><span className="mt-2 block text-2xl font-semibold">0%</span><span className="mt-1 block text-xs text-white/60">지급 구성은 펀드 내역으로 확인</span></div><div className="rounded-xl border border-white/15 p-4"><strong className="text-gold">신청 시점</strong><span className="mt-2 block text-lg font-semibold">출국 + 비자 종료 후</span><span className="mt-1 block text-xs text-white/60">공식 시스템이 실제 자격 확인</span></div></div></section>
<div className="mt-8"><DaspReadinessCheck/></div>
<section className="mt-10" aria-labelledby="dasp-steps"><h2 id="dasp-steps" className="text-2xl font-semibold text-navy">DASP 신청 방법</h2><ol className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><li className="rounded-2xl border border-border bg-white p-5"><span className="text-sm font-semibold text-gold">01 출국 전</span><h3 className="mt-2 font-semibold text-navy">Super 찾기</h3><p className="mt-2 text-sm leading-6 text-muted">myGov 연결 ATO 또는 각 펀드에서 계정과 고용주 납입 완료 여부를 확인하세요.</p></li><li className="rounded-2xl border border-border bg-white p-5"><span className="text-sm font-semibold text-gold">02 출국 후</span><h3 className="mt-2 font-semibold text-navy">모든 임시비자 종료 확인</h3><p className="mt-2 text-sm leading-6 text-muted">보유한 임시비자 중 하나라도 아직 유효하면 신청을 저장할 수 있어도 펀드로 제출할 수 없습니다.</p></li><li className="rounded-2xl border border-border bg-white p-5"><span className="text-sm font-semibold text-gold">03 온라인 신청</span><h3 className="mt-2 font-semibold text-navy">ATO DASP 시스템</h3><p className="mt-2 text-sm leading-6 text-muted">신원, 이전 비자와 각 Super 계정을 공식 시스템에서 확인해 신청하세요.</p></li><li className="rounded-2xl border border-border bg-white p-5"><span className="text-sm font-semibold text-gold">04 지급 후</span><h3 className="mt-2 font-semibold text-navy">명세 보관</h3><p className="mt-2 text-sm leading-6 text-muted">지급액과 원천징수 세금이 표시된 DASP payment summary를 보관하세요.</p></li></ol><div className="mt-5 flex flex-wrap gap-3"><a href="https://applicant.tr.super.ato.gov.au/applicants/default.aspx?pid=1" target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center rounded-lg bg-navy px-5 text-sm font-semibold text-white">ATO DASP 온라인 신청 &rarr;</a><a href="https://www.ato.gov.au/individuals-and-families/super-for-individuals-and-families/super/temporary-residents-and-superannuation" target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center rounded-lg border border-navy px-5 text-sm font-semibold text-navy">ATO 임시거주자 Super 안내 &rarr;</a></div></section>
<section id="dasp-after-submit" className="mt-10 scroll-mt-24 rounded-3xl border border-navy/20 bg-white p-5 sm:p-8" aria-labelledby="dasp-after-submit-heading">
  <p className="text-sm font-semibold text-gold">신청 전·후 막혔을 때</p>
  <h2 id="dasp-after-submit-heading" className="mt-2 text-2xl font-semibold text-navy">검색, 접수, 지급을 서로 다른 단계로 기록하세요</h2>
  <div className="mt-6 grid gap-4 lg:grid-cols-3">
    <article className="border-t-2 border-gold bg-surface p-5"><h3 className="font-semibold text-navy">1 · 펀드가 검색되지 않음</h3><p className="mt-2 text-sm leading-6 text-muted">최신 개인 statement의 펀드명·ABN·계정 정보를 본인의 안전한 기록과 대조하고 공식 시스템의 펀드 추가 신청 경로를 확인하세요. TFN 제공은 선택 사항이며, 제공하면 ATO 기록 검색에 도움이 될 수 있습니다. 이 사이트에는 번호를 입력하지 마세요.</p></article>
    <article className="border-t-2 border-gold bg-surface p-5"><h3 className="font-semibold text-navy">2 · 제출 내용에 오류가 있음</h3><p className="mt-2 text-sm leading-6 text-muted">제출 전 내용을 다시 확인하고 접수 이메일을 보관하세요. 이미 제출한 신청은 자유롭게 편집할 수 있다고 가정하지 말고, 오류가 있으면 해당 Super 펀드 또는 ATO에 연락해 처리 경로를 확인하세요. 먼저 재제출하거나 삭제하라고 권하지 않습니다.</p></article>
    <article className="border-t-2 border-gold bg-surface p-5"><h3 className="font-semibold text-navy">3 · 지급을 기다리는 중</h3><p className="mt-2 text-sm leading-6 text-muted">온라인에 신청서가 보이는 것만으로 처리 완료는 아닙니다. 펀드 보유분은 해당 펀드에, ATO 보유분은 ATO에 문의하세요. 일반적인 28일 안내는 기관이 필요한 자료를 모두 받은 뒤부터이며, 제출 버튼을 누른 뒤 28일 안에 입금된다는 보장이 아닙니다.</p></article>
  </div>
  <p className="mt-5 text-sm leading-7 text-muted">본인 기록에는 접수일, 추가 자료 요청일, 마지막 자료를 보낸 날, 다시 연락할 날을 나눠 적으세요. 아래 문장은 사용자가 공식 기관에 직접 문의할 때 복사하는 틀이며 이 사이트가 발송하지 않습니다.</p>
  <blockquote className="mt-4 break-words border-l-4 border-gold bg-surface p-5 text-sm leading-7 text-navy" lang="en">Have you received all required information for my DASP application? Is anything outstanding, and when should I follow up?</blockquote>
  <p className="mt-4 text-sm leading-7 text-muted">가상 예시: 접수 이메일은 받았지만 추가 신원 확인 요청에 아직 답하지 않았다면 ‘지급 완료’로 표시하지 않습니다. 요구 자료와 제출 경로를 먼저 확인하고, 실제 계좌 입금과 지급 명세를 대조한 뒤 완료로 표시하세요.</p>
</section>
<section className="mt-10 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-border bg-surface p-6"><h2 className="text-xl font-semibold text-navy">자주 놓치는 부분</h2><ul className="mt-4 space-y-2 text-sm leading-6 text-muted"><li>• 마지막 고용주의 Super가 입금되기 전에 계정을 닫지 않기</li><li>• DASP·Bond·마지막 급여를 받기 전 은행 지급 방법 확인</li><li>• 호주 전화번호 해지 전 모든 2단계 인증과 복구 수단 변경</li><li>• 여러 Super 펀드가 있으면 각각 검색·신청 대상인지 확인</li><li>• 6개월 뒤 ATO로 이전됐더라도 포기하지 말고 ATO-held super 확인</li></ul></div><div className="rounded-2xl border border-amber-300 bg-amber-50 p-6 text-sm leading-7 text-amber-950"><h2 className="font-semibold">세무·이민 안내</h2><p className="mt-1">DASP 자격, 세율, 비자 종료와 마지막 Tax return은 개인 사정에 따라 달라질 수 있습니다. DASP만을 위해 유효한 비자를 취소하면 향후 여행·신청에 영향을 줄 수 있으므로 먼저 Home Affairs 공식 안내 또는 등록 전문가에게 확인하세요. 이 페이지는 세무·이민·법률 자문이 아닙니다.</p></div></section>
</Container></main><Footer/></>}
