import Link from "next/link";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Container } from "@/components/ui/Container";
import { CareerPathwayExplorer } from "@/components/tools/CareerPathwayExplorer";
import { BreadcrumbJsonLd } from "@/components/seo/JsonLd";
import { createPageMetadata } from "@/lib/site";

export const metadata = createPageMetadata({ title: "호주 부족 직군·진로 탐색 | Hoju Compass", description: "호주 보건, 교육, 건설과 기술 직군의 하는 일과 준비 항목을 살펴보고 공식 부족·비자 목록을 구분해 확인하세요.", path: "/career-pathways" });

export default function CareerPathwaysPage() { return <><BreadcrumbJsonLd items={[{ name: "홈", path: "/" }, { name: "직업·진로 탐색", path: "/career-pathways" }]} /><Header /><main className="py-12 sm:py-16"><Container><Link href="/tools" className="inline-flex min-h-11 items-center text-sm font-medium text-muted hover:text-navy">&larr; 도구 목록으로 돌아가기</Link><div className="mt-5 max-w-4xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-gold">공식 자료로 시작하는 진로 탐색</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-navy sm:text-4xl">호주 직업·부족 분야 탐색기</h1><p className="mt-4 text-base leading-7 text-muted sm:text-lg">호주에서 수요가 논의되는 주요 분야와 직업의 실제 업무, 자격·면허 준비 항목을 살펴보세요. 노동시장 부족과 이민 비자 자격은 서로 다른 개념입니다.</p></div><div className="my-8 grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-gold/40 bg-gold/5 p-5"><h2 className="font-semibold text-navy">Occupation Shortage List</h2><p className="mt-2 text-sm leading-6 text-muted">고용주가 현재 인력을 구하기 어려운 직업을 지역별로 보여주는 노동시장 지표입니다. 부족 직업이어도 구직 경쟁은 있을 수 있습니다.</p><a href="https://www.jobsandskills.gov.au/data/occupation-shortage" target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-11 items-center text-sm font-semibold text-navy underline decoration-gold decoration-2 underline-offset-4">Jobs and Skills Australia에서 확인</a></div><div className="rounded-2xl border border-border bg-white p-5"><h2 className="font-semibold text-navy">Skilled Occupation List</h2><p className="mt-2 text-sm leading-6 text-muted">특정 기술 비자에서 고려될 수 있는 직업 목록입니다. 목록 포함만으로 비자 신청 자격이나 영주권이 보장되지 않습니다.</p><a href="https://immi.homeaffairs.gov.au/visas/working-in-australia/skill-occupation-list" target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-11 items-center text-sm font-semibold text-navy underline decoration-gold decoration-2 underline-offset-4">Home Affairs 공식 목록 확인</a></div></div><CareerPathwayExplorer /><section className="mt-10 rounded-2xl bg-navy p-6 text-white sm:p-8"><h2 className="text-xl font-semibold">중요한 이민 정보 안내</h2><p className="mt-3 max-w-4xl text-sm leading-7 text-white/70">Hoju Compass는 직업 정보와 공식 출처를 정리하지만 개인에게 어떤 비자를 신청해야 하는지 판단하거나 이민 전략을 추천하지 않습니다. 비자 요건은 변경될 수 있으므로 Home Affairs의 최신 정보와 등록된 이민 전문가를 확인하세요.</p></section></Container></main><Footer /></>;
}
