import Link from "next/link";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Container } from "@/components/ui/Container";
import { VehicleComparison } from "@/components/tools/VehicleComparison";
import { BreadcrumbJsonLd } from "@/components/seo/JsonLd";
import { createPageMetadata } from "@/lib/site";

export const metadata=createPageMetadata({title:"호주 중고차 구매 비교표 | Aussie Compass",description:"중고차 구매가와 Rego, 보험, 정비, 연료비를 비교하고 PPSR·VIN·사전검사 항목을 확인하세요.",path:"/used-car-comparison"});
export default function UsedCarComparisonPage(){return <><BreadcrumbJsonLd items={[{name:"홈",path:"/"},{name:"중고차 비교",path:"/used-car-comparison"}]}/><Header/><main className="py-12 sm:py-16"><Container><Link href="/tools" className="inline-flex min-h-11 items-center text-sm font-medium text-muted hover:text-navy">&larr; 도구 목록으로 돌아가기</Link><div className="mt-5 max-w-4xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-gold">호주 첫 차 프로젝트</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-navy sm:text-4xl">중고차 가격, 구매 후 비용까지 비교하세요</h1><p className="mt-4 text-base leading-7 text-muted sm:text-lg">저렴한 구매가만 보고 결정하면 Rego, 보험, 정비와 연료비가 예상보다 커질 수 있습니다. 최대 3대를 같은 기준으로 비교하고 구매 직전 확인을 챙기세요.</p></div>
<div className="my-8 grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-gold/40 bg-gold/5 p-5"><h2 className="font-semibold text-navy">PPSR은 구매 직전에</h2><p className="mt-2 text-sm leading-6 text-muted">공식 PPSR은 구매 당일 또는 전날 VIN으로 검색하고 증명서를 보관하세요.</p></article><article className="rounded-2xl border border-border bg-white p-5"><h2 className="font-semibold text-navy">독립적인 차량 검사</h2><p className="mt-2 text-sm leading-6 text-muted">PPSR에는 주행거리·소유 이력·차량 상태가 모두 나오지 않으므로 별도 검사가 필요합니다.</p></article><article className="rounded-2xl border border-border bg-white p-5"><h2 className="font-semibold text-navy">지역별 이전 비용</h2><p className="mt-2 text-sm leading-6 text-muted">Rego, CTP, 인지세와 이전 절차는 차량 등록 지역의 공식 기관에서 확인하세요.</p></article></div><VehicleComparison/>
<section className="mt-10 grid gap-4 sm:grid-cols-2"><a href="https://www.ppsr.gov.au/carcheck" target="_blank" rel="noreferrer" className="rounded-2xl bg-navy p-6 text-white"><strong className="text-lg">공식 PPSR Car Check &rarr;</strong><span className="mt-2 block text-sm leading-6 text-white/70">금융 이해관계, 도난·폐차 기록 검색</span></a><div className="rounded-2xl border border-amber-300 bg-amber-50 p-6 text-sm leading-7 text-amber-950"><h2 className="font-semibold">중요 안내</h2><p className="mt-1">이 도구는 차량 가치 평가나 기계 검사를 대신하지 않습니다. PPSR과 Rego 확인, 독립 정비사 검사, 보험 견적을 직접 완료한 뒤 결정하세요.</p></div></section></Container></main><Footer/></>}
