import Link from "next/link";
import { articles } from "@/data/articles";
import { Container } from "@/components/ui/Container";

export function ArticlesSection() {
  const latestArticles = articles.slice(-4).reverse();

  return <section className="bg-surface py-16 sm:py-24" aria-labelledby="resources-heading"><Container><div className="grid gap-6 border-b border-navy/20 pb-7 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-gold">Latest field notes</p><h2 id="resources-heading" className="mt-3 text-3xl font-semibold tracking-tight text-navy sm:text-4xl">이번 주에 먼저 확인할 생활 노트.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">일자리와 생활비처럼 실수하면 바로 비용이 되는 주제를 짧고 구체적으로 정리했습니다.</p></div><div className="flex flex-wrap items-center gap-x-6"><a href="/feed.xml" className="inline-flex min-h-11 items-center text-sm font-semibold text-muted hover:text-navy">RSS 구독 <span className="ml-2 font-mono text-gold" aria-hidden="true">+</span></a><Link href="/resources" className="inline-flex min-h-11 items-center text-sm font-semibold text-navy">전체 {articles.length}개 자료 보기 <span className="ml-3" aria-hidden="true">→</span></Link></div></div><ol>{latestArticles.map((article,index) => <li key={article.slug} className="border-b border-border"><Link href={`/resources/${article.slug}`} className="group grid gap-4 py-7 transition hover:bg-white/60 sm:grid-cols-[4rem_1fr_1.2fr_auto] sm:items-center sm:px-4"><span className="font-mono text-sm text-gold">{String(index+1).padStart(2,"0")}</span><span><span className="block text-xs font-semibold uppercase tracking-[0.14em] text-muted">{article.category} · {article.readingTime}</span><strong className="mt-2 block text-lg leading-7 text-navy">{article.title}</strong></span><span className="text-sm leading-6 text-muted">{article.description}</span><span className="text-xl text-navy transition group-hover:translate-x-1" aria-hidden="true">→</span></Link></li>)}</ol></Container></section>;
}
