import Link from "next/link";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Container } from "@/components/ui/Container";
import { BreadcrumbJsonLd } from "@/components/seo/JsonLd";
import { GlossaryExplorer, type GlossaryTerm } from "@/components/resources/GlossaryExplorer";
import { createPageMetadata } from "@/lib/site";

export const metadata = createPageMetadata({ title: "호주 생활 용어집 | TFN·ABN·Super·Bond 뜻", description: "호주 생활에서 자주 만나는 TFN, ABN, PAYG, Award, Super, VEVO, Bond, Rego와 DASP의 뜻과 확인할 점을 한국어로 찾아보세요.", path: "/glossary" });

const terms: GlossaryTerm[] = [
  { term: "ABN", korean: "호주 사업자 번호", category: "세금·연금", summary: "Australian Business Number. 사업체를 식별하는 11자리 번호입니다. 직원으로 일하는데 ABN 발급을 강요받는다면 고용관계가 잘못 분류된 것은 아닌지 확인해야 합니다.", check: "ABN이 있다는 사실만으로 업체의 면허·보험·신뢰성이 보장되지는 않습니다.", href: "/service-quote-comparator", source: "https://www.abr.gov.au/business-super-funds-charities/applying-abn" },
  { term: "Award", korean: "직종별 최저 고용기준", category: "일·급여", summary: "산업이나 직무에 적용되는 최저 시급, 수당, 근무시간과 휴식 기준을 정한 법적 문서입니다.", check: "내 직무에 적용되는 Award와 Classification 등급을 함께 확인하세요.", href: "/award-guide", source: "https://www.fairwork.gov.au/employment-conditions/awards" },
  { term: "Bond", korean: "렌트 보증금", category: "주거·교통", summary: "임대계약 의무를 지키지 않았을 때를 대비해 맡기는 금액입니다. 보관·청구 절차와 한도는 주·준주마다 다릅니다.", check: "현금이나 개인 계좌 송금 전 계약 당사자와 해당 지역의 공식 Bond 접수 절차를 확인하세요.", href: "/property-inspection-checklist" },
  { term: "Casual loading", korean: "캐주얼 가산액", category: "일·급여", summary: "캐주얼 직원에게 기본 시급 위에 추가되는 금액입니다. 대부분의 유급휴가 등 일부 정규직 권리가 없는 점을 보완하지만 적용률과 계산은 Award·Agreement를 확인해야 합니다.", check: "광고 시급에 loading이 포함됐는지, 주말·공휴일 penalty가 별도인지 Payslip과 Award에서 확인하세요.", href: "/casual-loading-guide", source: "https://www.fairwork.gov.au/starting-employment/types-of-employees/casual-employees" },
  { term: "Classification", korean: "직무 등급", category: "일·급여", summary: "Award 안에서 업무 난이도, 책임, 경험 등에 따라 나뉘는 급여 등급입니다. 같은 직종이어도 실제 업무에 따라 최저 시급이 달라질 수 있습니다.", check: "직함만 보지 말고 실제 하는 일을 Award의 등급 설명과 비교하세요.", href: "/award-guide", source: "https://www.fairwork.gov.au/employment-conditions/awards/award-classifications" },
  { term: "Condition report", korean: "입주 상태 기록", category: "주거·교통", summary: "입주 당시 벽, 바닥, 가전과 시설 상태를 기록한 문서입니다. 퇴거 때 손상 여부와 Bond 반환을 판단하는 주요 자료가 됩니다.", check: "입주 직후 날짜가 남는 사진·영상과 함께 꼼꼼히 수정해 정해진 기한 안에 제출하세요.", href: "/moving-checklist" },
  { term: "DASP", korean: "출국자 Super 지급", category: "세금·연금", summary: "Departing Australia Superannuation Payment. 자격이 되는 임시비자 소지자가 호주를 떠나 비자가 종료된 뒤 Super 지급을 신청하는 제도입니다.", check: "비자 상태, 출국 여부, 세율과 펀드별 신청 조건을 ATO에서 확인하세요.", href: "/leaving-australia-guide", source: "https://www.ato.gov.au/individuals-and-families/super-for-individuals-and-families/super/temporary-residents-and-superannuation/departing-australia-superannuation-payment-dasp" },
  { term: "EOFY", korean: "회계연도 말", category: "세금·연금", summary: "End of Financial Year. 호주의 개인 소득세 회계연도는 일반적으로 7월 1일부터 다음 해 6월 30일까지이며, 이후 Tax return 준비가 시작됩니다.", check: "Income statement가 tax ready인지 확인하고 영수증·공제 근거를 먼저 정리하세요.", href: "/tax-return-guide", source: "https://www.ato.gov.au/individuals-and-families/your-tax-return" },
  { term: "HAP ID", korean: "비자 신체검사 식별번호", category: "비자·정착", summary: "Home Affairs가 비자 신체검사 대상자에게 부여하는 식별번호입니다. 지정 병원 예약과 검사 결과 연결에 사용됩니다.", check: "요청받은 검사 항목과 HAP ID가 나온 referral letter를 확인한 뒤 예약하세요.", href: "/visa-preparation-guide", source: "https://immi.homeaffairs.gov.au/help-support/meeting-our-requirements/health/arrange-your-health-examinations" },
  { term: "ImmiAccount", korean: "호주 이민 온라인 계정", category: "비자·정착", summary: "비자 신청, 서류 첨부, 메시지와 진행 상태를 관리하는 Home Affairs 공식 온라인 계정입니다.", check: "검색 광고 속 유사 사이트가 아닌 공식 주소인지 확인하고 MFA와 복구 수단을 설정하세요.", href: "/visa-preparation-guide", source: "https://online.immi.gov.au/lusc/login" },
  { term: "Medicare", korean: "호주 공공 의료제도", category: "비자·정착", summary: "자격이 있는 사람에게 일부 의료비 지원을 제공하는 호주의 공공 의료제도입니다. 비자나 상호 의료협정 등에 따라 자격이 달라집니다.", check: "본인 비자의 Medicare 자격과 별도 보험 필요 여부를 Services Australia에서 확인하세요.", href: "/arrival-checklist", source: "https://www.servicesaustralia.gov.au/medicare" },
  { term: "MyGov", korean: "호주 정부 서비스 계정", category: "비자·정착", summary: "ATO, Medicare 등 여러 정부 서비스를 연결해 이용하는 온라인 계정입니다.", check: "공용기기에서 로그인하지 말고 강한 비밀번호와 MFA를 사용하세요.", href: "/arrival-checklist", source: "https://my.gov.au/" },
  { term: "NES", korean: "국가 고용 기준", category: "일·급여", summary: "National Employment Standards. 호주 국가 직장관계 제도에 속하는 직원에게 적용되는 최소 고용 권리입니다.", check: "Award나 계약이 NES보다 불리한 조건을 정할 수 있는지 추측하지 말고 Fair Work 안내를 확인하세요.", href: "/leave-guide", source: "https://www.fairwork.gov.au/employment-conditions/national-employment-standards" },
  { term: "OSHC", korean: "유학생 건강보험", category: "비자·정착", summary: "Overseas Student Health Cover. 대부분의 학생비자 소지자가 체류 중 유지해야 하는 의료보험입니다.", check: "대기기간, 제외 항목, 병원 청구 방식과 비자 전체 기간의 보장 여부를 비교하세요.", href: "/visa-preparation-guide", source: "https://www.privatehealth.gov.au/health_insurance/overseas/overseas_student_health_cover.htm" },
  { term: "PAYG withholding", korean: "급여 원천징수", category: "세금·연금", summary: "고용주가 급여에서 예상 세금을 미리 떼어 ATO에 납부하는 방식입니다. 최종 세액은 Tax return에서 정산됩니다.", check: "Payslip의 PAYG, Gross, Net과 ATO income statement가 서로 맞는지 확인하세요.", href: "/payslip-guide", source: "https://www.ato.gov.au/businesses-and-organisations/hiring-and-paying-your-workers/payg-withholding" },
  { term: "Payslip", korean: "급여명세서", category: "일·급여", summary: "급여 기간, 근무시간, 시급, Gross·Net pay, 공제와 Super 등을 보여주는 기록입니다.", check: "급여를 받은 뒤 이름, 기간, 시간, rate, loading·allowance와 공제 내역을 확인하고 보관하세요.", href: "/payslip-guide", source: "https://www.fairwork.gov.au/pay-and-wages/paying-wages/pay-slips" },
  { term: "Penalty rates", korean: "특정 시간대 가산임금", category: "일·급여", summary: "주말, 공휴일, 야간, 이른 아침 또는 초과근무처럼 특정 조건에 적용될 수 있는 더 높은 급여율입니다.", check: "무조건 같은 비율이 아니므로 적용 Award, 고용형태, 시간대와 근무일을 확인하세요.", href: "/award-guide", source: "https://www.fairwork.gov.au/pay-and-wages/penalty-rates-allowances-and-other-payments/penalty-rates" },
  { term: "PPSR", korean: "동산 담보·차량 이력 검색", category: "주거·교통", summary: "Personal Property Securities Register. 중고차 구매 전 금융 이해관계와 도난·폐차 기록 등을 VIN으로 확인하는 공식 등록부입니다.", check: "구매 당일 또는 전날 공식 검색을 하고 증명서를 보관하세요. 기계 상태 검사를 대신하지는 않습니다.", href: "/used-car-comparison", source: "https://www.ppsr.gov.au/carcheck" },
  { term: "Rego", korean: "차량 등록", category: "주거·교통", summary: "Registration의 일상적 표현입니다. 차량을 도로에서 합법적으로 운행하기 위한 주·준주별 등록 상태와 비용을 뜻합니다.", check: "번호판만 믿지 말고 해당 주의 공식 조회에서 VIN·차량 세부정보와 만료일을 대조하세요.", href: "/used-car-comparison" },
  { term: "Super", korean: "퇴직연금", category: "세금·연금", summary: "Superannuation. 고용주가 자격이 되는 직원의 노후를 위해 Super fund에 납부하는 금액입니다. 일반 급여와 입금 시점이 다를 수 있습니다.", check: "계약서·Payslip의 금액과 실제 펀드 계정 입금을 정기적으로 비교하세요.", href: "/super-guide", source: "https://www.ato.gov.au/individuals-and-families/super-for-individuals-and-families" },
  { term: "TFN", korean: "세금 파일 번호", category: "세금·연금", summary: "Tax File Number. ATO가 개인의 세금과 Super 기록을 관리할 때 사용하는 고유 번호입니다.", check: "TFN은 민감정보입니다. 채용 지원서나 집 계약 문의 등에 불필요하게 보내지 마세요.", href: "/arrival-checklist", source: "https://www.ato.gov.au/individuals-and-families/tax-file-number" },
  { term: "USI", korean: "교육 고유 식별번호", category: "비자·정착", summary: "Unique Student Identifier. 호주에서 국가 인정 교육·훈련 기록을 관리하는 개인 번호이며 대학생도 졸업 요건 등에 필요할 수 있습니다.", check: "여권상의 이름과 동일하게 만들고 기존 번호가 있다면 새로 만들지 말고 찾으세요.", href: "/arrival-checklist", source: "https://www.usi.gov.au/students/get-a-usi" },
  { term: "VEVO", korean: "비자 상태·조건 조회", category: "비자·정착", summary: "Visa Entitlement Verification Online. 현재 비자 정보와 근무·체류 조건을 온라인으로 확인하는 Home Affairs 서비스입니다.", check: "고용주나 집주인에게 여권 전체 사본을 보내기 전 필요한 정보만 안전하게 공유할 방법을 확인하세요.", href: "/arrival-checklist", source: "https://immi.homeaffairs.gov.au/visas/already-have-a-visa/check-visa-details-and-conditions/check-conditions-online" },
];

export default function GlossaryPage() {
  return <><BreadcrumbJsonLd items={[{ name: "홈", path: "/" }, { name: "실용 자료", path: "/resources" }, { name: "호주 생활 용어집", path: "/glossary" }]} /><Header /><main className="py-12 sm:py-16"><Container><Link href="/resources" className="inline-flex min-h-11 items-center text-sm font-medium text-muted hover:text-navy">&larr; 실용 자료로 돌아가기</Link><div className="mt-7 max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-gold">Australian life, translated</p><h1 className="mt-3 text-4xl font-semibold tracking-tight text-navy sm:text-5xl">처음 보는 호주 생활 용어,<br className="hidden sm:block" /> 뜻부터 확인할 것까지.</h1><p className="mt-5 max-w-3xl text-base leading-7 text-muted sm:text-lg">급여명세서, 비자 안내, 렌트 계약에서 반복해서 만나는 약어를 한국어로 풀었습니다. 간단한 뜻을 확인한 뒤 관련 가이드와 정부기관 원문으로 이어가세요.</p></div><GlossaryExplorer terms={terms} /><section className="mt-12 grid gap-5 border-t border-navy/20 pt-8 md:grid-cols-2"><div><h2 className="text-xl font-semibold text-navy">이 용어집의 범위</h2><p className="mt-3 text-sm leading-7 text-muted">빠른 이해를 위한 일반 설명이며 계약, 세무, 고용, 이민 또는 법률 자문이 아닙니다. 권리와 비용은 비자·고용형태·지역·시점에 따라 달라질 수 있습니다.</p></div><div><h2 className="text-xl font-semibold text-navy">결정하기 전에는</h2><p className="mt-3 text-sm leading-7 text-muted">각 항목의 공식 설명과 본인에게 적용되는 문서를 다시 확인하세요. 문제가 급하거나 안전이 염려되면 용어 검색보다 공식 도움 연락처를 먼저 이용하세요.</p><Link href="/help-directory" className="mt-3 inline-flex min-h-11 items-center font-semibold text-navy underline decoration-gold decoration-2 underline-offset-4">도움 연락처 확인 &rarr;</Link></div></section></Container></main><Footer /></>;
}
