"use client";

import { useMemo, useState } from "react";

type Career = { title: string; korean: string; sector: string; work: string; preparation: string[]; usefulFor: string; searchTerms: string };

const careers: Career[] = [
  { title: "Registered Nurse", korean: "간호사", sector: "Health", work: "병원, 클리닉, 노인 돌봄 등에서 환자를 평가하고 간호 계획과 치료를 수행합니다.", preparation: ["호주 인정 간호 교육", "AHPRA 등록 요건 확인", "직무별 영어·실습 요건 확인"], usefulFor: "Health는 최근 공식 부족 분석에서 지속적으로 언급되는 핵심 분야입니다.", searchTerms: "registered nurse nursing 간호 보건 health" },
  { title: "Early Childhood Teacher", korean: "유아교사", sector: "Education", work: "유아의 발달과 학습을 계획하고 가정·교육기관과 협력합니다.", preparation: ["인정되는 교육 과정 확인", "주별 등록·Working with Children 요건", "영어 및 실습 요건"], usefulFor: "Education은 공식 부족 분석에서 주요 분야로 다뤄집니다.", searchTerms: "early childhood teacher childcare 유아 교육 education" },
  { title: "Secondary School Teacher", korean: "중등교사", sector: "Education", work: "전공 과목을 가르치고 학습 계획, 평가와 학생 지원을 담당합니다.", preparation: ["교원 교육 과정", "주·준주 교사 등록", "전공과 실습 인정 여부"], usefulFor: "지역과 과목에 따라 수요가 크게 달라질 수 있어 주별 확인이 중요합니다.", searchTerms: "secondary school teacher high school 중등 교사 education" },
  { title: "Electrician", korean: "전기 기술자", sector: "Construction & Trades", work: "건물과 설비의 전기 배선, 장비 설치, 검사와 수리를 수행합니다.", preparation: ["호주 견습·자격 경로 확인", "주별 전기 면허", "해외 경력·자격 인정 여부"], usefulFor: "Trade와 Construction은 최근 공식 부족 분석에서 비중이 큰 분야입니다.", searchTerms: "electrician electrical 전기 기술 trade construction" },
  { title: "Plumber", korean: "배관 기술자", sector: "Construction & Trades", work: "급수, 배수, 가스와 관련 설비를 설치하고 유지·보수합니다.", preparation: ["Certificate·Apprenticeship 경로", "주별 등록과 면허", "가스 작업 등 추가 승인 범위"], usefulFor: "면허 범위가 주마다 다르므로 거주 지역 기준으로 확인해야 합니다.", searchTerms: "plumber plumbing 배관 설비 trade construction" },
  { title: "Carpenter", korean: "목수", sector: "Construction & Trades", work: "건축 현장에서 목재 구조물, 프레임과 내·외장 요소를 제작·설치합니다.", preparation: ["견습·직업교육 과정", "White Card 등 현장 요건", "경력과 기술 평가 가능성 확인"], usefulFor: "건설 경기와 지역에 따라 채용 수요가 달라질 수 있습니다.", searchTerms: "carpenter carpentry 목수 건축 trade construction" },
  { title: "Motor Mechanic", korean: "자동차 정비사", sector: "Automotive", work: "차량의 고장을 진단하고 엔진, 제동과 전기 시스템을 정비합니다.", preparation: ["자동차 정비 직업교육", "주별 수리업 관련 요건", "제조사·전기차 기술 추가 교육"], usefulFor: "세부 전문 분야와 지역에 따라 구인 난이도가 다릅니다.", searchTerms: "motor mechanic automotive 자동차 정비 기술" },
  { title: "Civil Engineer", korean: "토목 엔지니어", sector: "Engineering", work: "도로, 교량, 수자원과 건설 프로젝트를 설계·관리하고 안전성을 검토합니다.", preparation: ["인정 공학 학위", "기술 평가·전문 등록 확인", "현지 기준과 프로젝트 경험"], usefulFor: "공학 분야는 자격만큼 관련 경험과 세부 전문성이 중요합니다.", searchTerms: "civil engineer engineering 토목 엔지니어 건설" },
];

const sectors = ["전체", ...Array.from(new Set(careers.map((career) => career.sector)))];

export function CareerPathwayExplorer() {
  const [query, setQuery] = useState("");
  const [sector, setSector] = useState("전체");
  const filtered = useMemo(() => careers.filter((career) => (sector === "전체" || career.sector === sector) && career.searchTerms.toLowerCase().includes(query.trim().toLowerCase())), [query, sector]);
  return <div><section className="rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-7" aria-labelledby="career-filter-heading"><h2 id="career-filter-heading" className="text-xl font-semibold text-navy">직업 분야 살펴보기</h2><p className="mt-2 text-sm leading-6 text-muted">이 목록은 진로 탐색용이며 현재 부족 여부나 비자 자격을 판정하지 않습니다.</p><div className="mt-5 grid gap-4 sm:grid-cols-[minmax(0,1fr)_240px]"><label className="text-sm font-medium text-navy">직업 검색<input value={query} onChange={(e) => setQuery(e.target.value)} className="mt-1.5 min-h-11 w-full rounded-lg border border-border px-3 py-2 outline-none focus:border-navy focus:ring-2 focus:ring-navy/15" placeholder="예: 간호사, Electrician" /></label><label className="text-sm font-medium text-navy">분야<select value={sector} onChange={(e) => setSector(e.target.value)} className="mt-1.5 min-h-11 w-full rounded-lg border border-border bg-white px-3 py-2">{sectors.map((item) => <option key={item}>{item}</option>)}</select></label></div></section><p className="mt-6 text-sm text-muted">{filtered.length}개 직업</p><ul className="mt-4 grid gap-5 lg:grid-cols-2">{filtered.map((career) => <li key={career.title} className="rounded-2xl border border-border bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-gold">{career.sector}</p><h2 className="mt-2 text-xl font-semibold text-navy">{career.title}</h2><p className="mt-1 text-sm font-medium text-muted">{career.korean}</p><p className="mt-4 text-sm leading-6 text-muted">{career.work}</p><h3 className="mt-5 text-sm font-semibold text-navy">준비할 때 확인할 것</h3><ul className="mt-2 space-y-2">{career.preparation.map((item) => <li key={item} className="flex gap-2 text-sm leading-6 text-muted"><span className="text-gold">•</span>{item}</li>)}</ul><p className="mt-5 rounded-xl bg-surface p-4 text-sm leading-6 text-muted">{career.usefulFor}</p></li>)}</ul>{!filtered.length && <div className="mt-4 rounded-xl bg-surface p-8 text-center text-muted">검색 조건에 맞는 직업이 없습니다.</div>}</div>;
}
