"use client";
import { useMemo, useState } from "react";
import { careerSectors as sectors, findCareers } from "@/data/careerPathways";

export function CareerPathwayExplorer() {
  const [query, setQuery] = useState("");
  const [sector, setSector] = useState("전체");
  const filtered = useMemo(() => findCareers(query, sector), [query, sector]);
  return <div><section className="rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-7" aria-labelledby="career-filter-heading"><h2 id="career-filter-heading" className="text-xl font-semibold text-navy">직업 분야 살펴보기</h2><p className="mt-2 text-sm leading-6 text-muted">이 목록은 진로 탐색용이며 현재 부족 여부나 비자 자격을 판정하지 않습니다.</p><div className="mt-5 grid gap-4 sm:grid-cols-[minmax(0,1fr)_240px]"><label className="text-sm font-medium text-navy">직업 검색<input value={query} onChange={(e) => setQuery(e.target.value)} className="mt-1.5 min-h-11 w-full rounded-lg border border-border px-3 py-2 outline-none focus:border-navy focus:ring-2 focus:ring-navy/15" placeholder="예: 간호사, Electrician" /></label><label className="text-sm font-medium text-navy">분야<select value={sector} onChange={(e) => setSector(e.target.value)} className="mt-1.5 min-h-11 w-full rounded-lg border border-border bg-white px-3 py-2">{sectors.map((item) => <option key={item}>{item}</option>)}</select></label></div></section><p className="mt-6 break-words text-sm text-muted" role="status">{filtered.length}개 직업 · 분야: {sector}{query.trim() ? ` · 검색: ${query.trim()}` : ""}</p><ul className="mt-4 grid gap-5 lg:grid-cols-2">{filtered.map((career) => <li key={career.title} className="rounded-2xl border border-border bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-gold">{career.sector}</p><h2 className="mt-2 text-xl font-semibold text-navy">{career.title}</h2><p className="mt-1 text-sm font-medium text-muted">{career.korean}</p><p className="mt-4 text-sm leading-6 text-muted">{career.work}</p><h3 className="mt-5 text-sm font-semibold text-navy">첫 확인</h3><p className="mt-2 text-sm leading-7 text-muted">{career.first}</p><h3 className="mt-4 text-sm font-semibold text-navy">준비할 자료</h3><p className="mt-2 text-sm leading-7 text-muted">{career.documents}</p><h3 className="mt-4 text-sm font-semibold text-navy">다음 질문</h3><p className="mt-2 text-sm leading-7 text-muted">{career.question}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2">{career.links.map(link => <a key={link.href} href={link.href} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center text-sm font-semibold text-navy underline">{link.label} ↗</a>)}</div><p className="mt-5 rounded-xl bg-surface p-4 text-sm leading-6 text-muted">{career.usefulFor}</p></li>)}</ul>{!filtered.length && <div className="mt-4 rounded-xl bg-surface p-8 text-center text-muted">검색 조건에 맞는 직업이 없습니다. 현재 분야는 {sector}입니다.<button type="button" onClick={() => { setQuery(""); setSector("전체"); }} className="mx-auto mt-3 block min-h-11 rounded-lg border border-navy px-4 font-semibold text-navy">검색·분야 초기화</button></div>}</div>;
}
