"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type RecordItem={id:string;category:string;state:string;period:string;timing:string;status:string;callout:number;labour:number;materials:number;other:number;itemised:boolean};
const storageKey="aussie-compass-service-price-log-v1";
const categories=["Plumbing","Electrical","Cleaning","Removalist","Locksmith","Pest control","Appliance repair","Other"];
const states=["NSW","VIC","QLD","WA","SA","TAS","ACT","NT"];
const total=(item:RecordItem)=>item.callout+item.labour+item.materials+item.other;

export function ServicePriceLog(){
 const [records,setRecords]=useState<RecordItem[]>([]);const [loaded,setLoaded]=useState(false);const [category,setCategory]=useState(categories[0]);const [state,setState]=useState(states[0]);const [period,setPeriod]=useState("");const [timing,setTiming]=useState("standard");const [status,setStatus]=useState("completed");const [callout,setCallout]=useState("");const [labour,setLabour]=useState("");const [materials,setMaterials]=useState("");const [other,setOther]=useState("");const [itemised,setItemised]=useState(false);
 useEffect(()=>{try{const saved=localStorage.getItem(storageKey);if(saved)setRecords(JSON.parse(saved))}catch{}setLoaded(true)},[]);useEffect(()=>{if(!loaded)return;try{localStorage.setItem(storageKey,JSON.stringify(records))}catch{}},[records,loaded]);
 const summaries=useMemo(()=>categories.map((name)=>{const matches=records.filter((item)=>item.category===name).map(total).sort((a,b)=>a-b);if(!matches.length)return null;const middle=Math.floor(matches.length/2);const median=matches.length%2?matches[middle]:(matches[middle-1]+matches[middle])/2;return{name,count:matches.length,median,min:matches[0],max:matches.at(-1)||0}}).filter(Boolean) as Array<{name:string;count:number;median:number;min:number;max:number}>,[records]);
 function submit(event:FormEvent){event.preventDefault();const values=[callout,labour,materials,other].map((value)=>Math.max(0,Number(value)||0));if(values.every((value)=>value===0))return;setRecords((current)=>[{id:crypto.randomUUID(),category,state,period,timing,status,callout:values[0],labour:values[1],materials:values[2],other:values[3],itemised},...current]);setCallout("");setLabour("");setMaterials("");setOther("");setItemised(false)}
 return <section className="rounded-3xl border border-border bg-white p-5 shadow-sm sm:p-8" aria-labelledby="price-log-heading"><div><p className="text-sm font-semibold text-gold">공개 전 개인 데이터부터</p><h2 id="price-log-heading" className="mt-2 text-2xl font-semibold text-navy">내 서비스 가격 기록</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">업체명, 작업자 이름, 전화번호, 주소나 자유서술 리뷰를 받지 않습니다. 넓은 지역과 가격 구성만 현재 브라우저에 저장합니다.</p></div>
 <form onSubmit={submit} className="mt-7 rounded-2xl bg-surface p-4 sm:p-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-medium text-navy">서비스<select value={category} onChange={(e)=>setCategory(e.target.value)} className="mt-2 min-h-11 w-full rounded-lg border border-border bg-white px-3">{categories.map((value)=><option key={value}>{value}</option>)}</select></label><label className="text-sm font-medium text-navy">주·준주<select value={state} onChange={(e)=>setState(e.target.value)} className="mt-2 min-h-11 w-full rounded-lg border border-border bg-white px-3">{states.map((value)=><option key={value}>{value}</option>)}</select></label><label className="text-sm font-medium text-navy">월 (선택)<input type="month" value={period} onChange={(e)=>setPeriod(e.target.value)} className="mt-2 min-h-11 w-full rounded-lg border border-border bg-white px-3"/></label><label className="text-sm font-medium text-navy">시간대<select value={timing} onChange={(e)=>setTiming(e.target.value)} className="mt-2 min-h-11 w-full rounded-lg border border-border bg-white px-3"><option value="standard">일반 시간</option><option value="afterhours">야간·주말·긴급</option></select></label><label className="text-sm font-medium text-navy">기록 유형<select value={status} onChange={(e)=>setStatus(e.target.value)} className="mt-2 min-h-11 w-full rounded-lg border border-border bg-white px-3"><option value="completed">결제 완료</option><option value="quote">견적만 받음</option></select></label>{[[callout,setCallout,"출장비"],[labour,setLabour,"인건비"],[materials,setMaterials,"자재비"],[other,setOther,"기타 비용"]].map(([value,setValue,label])=><label key={label as string} className="text-sm font-medium text-navy">{label as string} ($)<input type="number" min="0" step="0.01" value={value as string} onChange={(e)=>(setValue as (value:string)=>void)(e.target.value)} className="mt-2 min-h-11 w-full rounded-lg border border-border bg-white px-3"/></label>)}</div><div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><label className="flex cursor-pointer items-center gap-3 text-sm text-navy"><input type="checkbox" checked={itemised} onChange={(e)=>setItemised(e.target.checked)} className="h-5 w-5 accent-[var(--color-gold)]"/>항목별 견적·청구서 확인</label><button type="submit" className="min-h-11 rounded-lg bg-navy px-5 text-sm font-semibold text-white">가격 기록 추가</button></div></form>
 {summaries.length>0&&<div className="mt-8"><h3 className="text-lg font-semibold text-navy">내 기록 요약</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{summaries.map((summary)=><div key={summary.name} className="rounded-xl border border-border p-4"><div className="flex justify-between"><strong className="text-navy">{summary.name}</strong><span className="text-xs text-muted">{summary.count}건</span></div><p className="mt-3 text-sm text-muted">중앙값 <strong className="text-lg text-navy">${summary.median.toFixed(2)}</strong></p><p className="mt-1 text-xs text-muted">내 범위 ${summary.min.toFixed(2)}–${summary.max.toFixed(2)}</p></div>)}</div></div>}
 <div className="mt-8 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b border-border text-xs text-muted"><th className="p-3">서비스</th><th className="p-3">지역·시기</th><th className="p-3">조건</th><th className="p-3">합계</th><th className="p-3">항목별</th><th className="p-3"><span className="sr-only">작업</span></th></tr></thead><tbody>{records.map((item)=><tr key={item.id} className="border-b border-border"><td className="p-3 font-medium text-navy">{item.category}</td><td className="p-3 text-muted">{item.state} · {item.period||"시기 미입력"}</td><td className="p-3 text-muted">{item.timing==="afterhours"?"야간·긴급":"일반"} · {item.status==="completed"?"결제":"견적"}</td><td className="p-3 font-semibold text-navy">${total(item).toFixed(2)}</td><td className="p-3 text-muted">{item.itemised?"확인":"미확인"}</td><td className="p-3 text-right"><button type="button" onClick={()=>setRecords((current)=>current.filter((value)=>value.id!==item.id))} className="min-h-10 px-2 text-xs font-semibold text-muted">삭제</button></td></tr>)}</tbody></table>{!records.length&&<p className="py-10 text-center text-sm text-muted">아직 저장된 가격 기록이 없습니다.</p>}</div></section>
}
