import Link from "next/link";
import {Header} from "@/components/layout/Header";import {Footer} from "@/components/layout/Footer";import {Container} from "@/components/ui/Container";import {LocalProjectChecklist,type ProjectGroup} from "@/components/tools/LocalProjectChecklist";import {VisaCostPlanner} from "@/components/tools/VisaCostPlanner";import {BreadcrumbJsonLd} from "@/components/seo/JsonLd";import {createPageMetadata} from "@/lib/site";

export const metadata=createPageMetadata({title:"호주 비자 신청 준비와 신체검사 안내 | Hoju Compass",description:"호주 비자 탐색, ImmiAccount, 서류, 비용, HAP ID, 호주 내 Bupa와 해외 Panel Physician 신체검사 절차를 단계별로 확인하세요.",path:"/visa-preparation-guide"});
const visaGroups:ProjectGroup[]=[
 {title:"1. 비자 확인",items:[{id:"finder",label:"공식 Visa Finder로 후보 확인",detail:"Visa Finder도 추천이나 승인 가능성을 보장하지 않으므로 각 비자 페이지를 다시 확인하세요."},{id:"subclass",label:"정확한 Subclass·Stream 페이지 읽기",detail:"자격, 체류조건, 신청 위치, 비용과 단계별 안내를 저장하세요."},{id:"passport",label:"여권 정보와 유효기간 확인",detail:"신청서와 증빙의 영문 이름·생년월일이 일치하는지 확인하세요."}]},
 {title:"2. 서류·비용 준비",items:[{id:"documents",label:"해당 비자의 서류 목록 작성",detail:"신원, 재정, 학업·경력 등 실제 비자 페이지에서 요구하는 항목만 준비하세요."},{id:"translations",label:"비영문 문서 번역 기준 확인",detail:"원본과 번역본, 번역자 정보 등 해당 비자 페이지의 최신 기준을 따르세요."},{id:"costs",label:"신청비와 별도 비용 예산",detail:"신체검사, 경찰증명, 생체정보, 번역과 보험은 신청비에 포함되지 않을 수 있습니다."}]},
 {title:"3. 신청·제출",items:[{id:"account",label:"공식 ImmiAccount와 MFA 설정",detail:"검색 광고나 대행 사이트가 아닌 Home Affairs 주소에서 접속하세요."},{id:"review",label:"제출 전 모든 답변·첨부 재검토",detail:"추측하지 말고 사실과 문서가 불일치하면 제출 전에 확인하세요."},{id:"copy",label:"제출본·TRN·결제 영수증 보관",detail:"제출한 답변과 첨부 파일의 사본을 안전하게 보관하세요."}]},
 {title:"4. 제출 후",items:[{id:"messages",label:"ImmiAccount 메시지와 Actions required 확인",detail:"추가 서류, 신체검사, 생체정보나 Character 요청을 놓치지 마세요."},{id:"changes",label:"상황·연락처 변경 알림",detail:"결혼, 이혼, 출생, 이름 또는 연락처 변경 등은 공식 절차로 업데이트하세요."},{id:"decision",label:"비자 결정문과 조건 직접 확인",detail:"VEVO와 결정문에서 근무·학업·체류 조건과 기간을 확인하세요."}]},
];

export default function VisaPreparationGuidePage(){return <><BreadcrumbJsonLd items={[{name:"홈",path:"/"},{name:"비자 신청 준비",path:"/visa-preparation-guide"}]}/><Header/><main className="py-12 sm:py-16"><Container><Link href="/tools" className="inline-flex min-h-11 items-center text-sm font-medium text-muted hover:text-navy">&larr; 도구 목록으로 돌아가기</Link><div className="mt-5 max-w-4xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-gold">호주 생활의 첫 단계</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-navy sm:text-4xl">호주 비자 신청, 공식 절차를 따라 준비하세요</h1><p className="mt-4 text-base leading-7 text-muted sm:text-lg">비자를 대신 선택하거나 승인 가능성을 판단하지 않습니다. 정확한 비자 페이지를 찾고, 신청·서류·비용·신체검사를 순서대로 준비할 수 있게 공식 경로를 정리했습니다.</p></div>
<section className="my-8 grid gap-4 md:grid-cols-3"><a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-finder" target="_blank" rel="noreferrer" className="rounded-2xl border border-gold/40 bg-gold/5 p-5"><p className="text-sm font-semibold text-gold">STEP 1</p><h2 className="mt-2 font-semibold text-navy">Visa Finder &rarr;</h2><p className="mt-2 text-sm leading-6 text-muted">가능한 비자 유형을 찾는 출발점이며 추천이나 승인 보장은 아닙니다.</p></a><a href="https://online.immi.gov.au/lusc/login" target="_blank" rel="noreferrer" className="rounded-2xl border border-border bg-white p-5"><p className="text-sm font-semibold text-gold">STEP 2</p><h2 className="mt-2 font-semibold text-navy">ImmiAccount &rarr;</h2><p className="mt-2 text-sm leading-6 text-muted">신청서 작성, 첨부, 메시지와 후속 요청을 관리하는 공식 계정입니다.</p></a><a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/fees-and-charges" target="_blank" rel="noreferrer" className="rounded-2xl border border-border bg-white p-5"><p className="text-sm font-semibold text-gold">STEP 3</p><h2 className="mt-2 font-semibold text-navy">Visa Pricing Estimator &rarr;</h2><p className="mt-2 text-sm leading-6 text-muted">신청 시점과 조건에 맞는 최신 신청비를 공식 도구에서 확인하세요.</p></a></section>
<LocalProjectChecklist storageKey="visa-preparation-project" eyebrow="개인정보는 입력하지 않는 진행표" title="비자 신청 준비 체크리스트" description="진행 여부만 현재 브라우저에 저장합니다. 여권번호, HAP ID, TRN, 건강정보와 신청 답변은 이 페이지에 입력하지 마세요." groups={visaGroups}/>
<section className="mt-10 border-l-4 border-gold bg-surface p-6 sm:p-8" aria-labelledby="visa-document-follow-up-heading">
  <h2 id="visa-document-follow-up-heading" className="text-2xl font-semibold text-navy">서류는 요구서 → 내 파일 → 제출 확인으로 대조하세요</h2>
  <p className="mt-3 text-sm leading-7 text-muted">본인의 안전한 폴더에 요구 항목·원본·번역본·첨부할 신청자·현재 상태·요청 기한을 표로 정리하세요. 가상의 재직증명서라면 발급 대기, 번역 대기, 제출 완료를 따로 표시합니다. 파일을 가지고 있다는 사실만으로 제출을 완료한 것은 아닙니다.</p>
  <ol className="mt-4 list-decimal space-y-3 pl-5 text-sm leading-7 text-muted">
    <li>올리기 전에 이름·발급일·전체 페이지와 스캔의 가독성을 확인하고, 실제 제출할 원본·번역본의 사본을 별도로 보관하세요.</li>
    <li>Home Affairs는 업로드한 첨부 문서를 ImmiAccount에서 다시 열 수 없으므로 본인 사본을 보관하라고 안내합니다. 화면에서 확인할 수 있는 첨부 목록·신청자·파일명·제출 상태를 본인 기록과 대조하세요.</li>
    <li>추가 요청은 해당 요구 항목·요청서의 기한·본인의 제출 증거를 함께 보관하세요. 기한은 개인에게 온 공문을 따르며 모든 신청에 같은 일수가 적용되는 것은 아닙니다.</li>
  </ol>
  <p className="mt-4 text-sm font-medium leading-7 text-navy">이 표와 첨부 파일·신청 번호·민감한 내용은 Hoju Compass에 입력하지 마세요. 이 페이지에는 진행 체크만 남깁니다.</p>
  <a href="https://immi.homeaffairs.gov.au/help-support/applying-online-or-on-paper/online/attach-documents-to-your-application" target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-11 items-center font-semibold text-navy underline decoration-gold underline-offset-4">Home Affairs 첨부 문서·사본 보관 안내 ↗</a>
</section>
<section className="mt-10" aria-labelledby="medical-heading"><div className="max-w-4xl"><p className="text-sm font-semibold text-gold">신체검사 상세 안내</p><h2 id="medical-heading" className="mt-2 text-3xl font-semibold text-navy">아무 병원에서 받을 수 있는 검사가 아닙니다</h2><p className="mt-3 leading-7 text-muted">모든 신청자가 같은 검사를 받는 것은 아닙니다. ImmiAccount의 Health assessment 또는 Home Affairs 요청서에서 필요한 검사와 HAP ID가 나온 뒤 지정 기관에 예약하는 것이 기본 흐름입니다.</p></div>
<ol className="mt-7 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><li className="rounded-2xl border border-border bg-white p-5"><span className="text-sm font-semibold text-gold">01</span><h3 className="mt-2 font-semibold text-navy">요청 여부 확인</h3><p className="mt-2 text-sm leading-6 text-muted">ImmiAccount → View details → Health assessment에서 Organise health examinations가 있는지 확인합니다.</p></li><li className="rounded-2xl border border-border bg-white p-5"><span className="text-sm font-semibold text-gold">02</span><h3 className="mt-2 font-semibold text-navy">HAP ID 확인</h3><p className="mt-2 text-sm leading-6 text-muted">Referral letter의 HAP ID와 필요한 검사 코드(예: 501·502)를 확인합니다.</p></li><li className="rounded-2xl border border-border bg-white p-5"><span className="text-sm font-semibold text-gold">03</span><h3 className="mt-2 font-semibold text-navy">지정 기관 예약</h3><p className="mt-2 text-sm leading-6 text-muted">호주 안은 Bupa MVS, 해외는 Home Affairs가 지정한 Panel Physician만 이용합니다.</p></li><li className="rounded-2xl border border-border bg-white p-5"><span className="text-sm font-semibold text-gold">04</span><h3 className="mt-2 font-semibold text-navy">제출 상태 확인</h3><p className="mt-2 text-sm leading-6 text-muted">검사 후 eMedical Client 또는 ImmiAccount에서 제출 여부를 확인합니다.</p></li></ol></section>
<section className="mt-8 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl bg-navy p-6 text-white sm:p-8"><p className="text-sm font-semibold text-gold">현재 호주 안에 있다면</p><h2 className="mt-2 text-2xl font-semibold">Bupa Medical Visa Services</h2><p className="mt-3 text-sm leading-7 text-white/70">Home Affairs가 안내하는 호주 내 Migration Medical Services Provider입니다. HAP ID가 필요하며 예약 화면에서 검사 항목과 현재 비용을 확인하세요.</p><div className="mt-5 flex flex-wrap gap-3"><a href="https://www.bupa.com.au/bupamvs" target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center rounded-lg bg-gold px-4 text-sm font-semibold text-navy">센터·예약 확인 &rarr;</a><a href="tel:1300794919" className="inline-flex min-h-11 items-center rounded-lg border border-white/20 px-4 text-sm font-semibold">1300 794 919</a></div></div><div className="rounded-3xl border border-border bg-white p-6 sm:p-8"><p className="text-sm font-semibold text-gold">한국 등 호주 밖에 있다면</p><h2 className="mt-2 text-2xl font-semibold text-navy">공식 Panel Physician 검색</h2><p className="mt-3 text-sm leading-7 text-muted">일반 병원 목록을 고정해서 제공하면 변경을 놓칠 수 있습니다. Home Affairs 국가 선택 메뉴에서 현재 승인된 병원·의사와 연락처를 직접 확인하세요.</p><a href="https://immi.homeaffairs.gov.au/contact-us-subsite/Pages/offices-outside-Australia.aspx" target="_blank" rel="noreferrer" className="mt-5 inline-flex min-h-11 items-center rounded-lg bg-navy px-4 text-sm font-semibold text-white">국가별 지정 병원 찾기 &rarr;</a></div></section>
<section className="mt-8 rounded-2xl border border-border bg-surface p-6 sm:p-8"><h2 className="text-xl font-semibold text-navy">검사 비용은 이렇게 확인하세요</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><div className="rounded-xl bg-white p-4"><strong className="text-navy">검사 종류</strong><p className="mt-2 text-sm leading-6 text-muted">Medical examination(501), chest x-ray(502), 혈액·추가 검사는 요청서에 따라 달라집니다.</p></div><div className="rounded-xl bg-white p-4"><strong className="text-navy">호주 내 비용</strong><p className="mt-2 text-sm leading-6 text-muted">Bupa 예약 과정에서 HAP ID에 연결된 항목과 결제 전 현재 총액을 확인하세요.</p></div><div className="rounded-xl bg-white p-4"><strong className="text-navy">해외 비용</strong><p className="mt-2 text-sm leading-6 text-muted">국가별 지정 클리닉이 현지 비용을 안내하므로 예약 전에 포함 항목과 추가 검사비를 문의하세요.</p></div></div><p className="mt-4 text-sm leading-6 text-muted">비자 신청비와 의료검사비는 별도일 수 있고, 추가 검사·전문의 소견·교통·번역 비용이 더 발생할 수 있습니다. 고정 가격표 대신 예약 직전 공식 금액을 확인하도록 구성했습니다.</p></section>
<div className="mt-10"><VisaCostPlanner/></div>
<section className="mt-10 border border-border bg-white p-6 sm:p-8" aria-labelledby="visa-health-deadline-heading">
  <h2 id="visa-health-deadline-heading" className="text-2xl font-semibold text-navy">검사 예약이 요청서의 기한보다 늦다면</h2>
  <p className="mt-3 text-sm leading-7 text-muted">Request for Health Examination의 검사 항목·HAP ID·기한부터 읽고 공식 예약 가능일과 대조하세요. 일부 신청자는 신청 전 사전 검사 경로를 이용할 수 있으므로 본인에게 적용되는 공식 절차를 먼저 확인합니다.</p>
  <p className="mt-4 rounded-xl bg-surface p-4 text-sm leading-7 text-navy"><strong>가상 예시:</strong> 요청서 기한은 9월 20일인데 가장 빠른 예약이 9월 24일이라면, 예약만으로 기한이 늘어난다고 생각하지 마세요. 기한 내 검사가 어려운 사정을 ImmiAccount에 첨부해 Department에 알리고, 예약 확인서와 가능한 날짜 등 실제 자료를 따로 보관하세요. 연장이 승인되거나 특정 기간이 허용된다는 보장은 아닙니다.</p>
  <p className="mt-4 text-sm leading-7 text-muted">Bupa 예약에 갈 수 없다면 기존 예약의 Modify/Cancel Booking 경로나 안내된 연락처를 이용하세요. 변경에는 예약에 사용한 HAP ID가 필요합니다. 예약을 방치하거나 중복 예약부터 만들지 말고, 해외 검사는 해당 지정 클리닉의 변경 절차를 확인하세요.</p>
  <a href="https://immi.homeaffairs.gov.au/help-support/meeting-our-requirements/health/arrange-your-health-examinations" target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-11 items-center font-semibold text-navy underline decoration-gold underline-offset-4">Home Affairs 검사 기한·예약 변경 안내 ↗</a>
</section>
<section className="mt-8 border border-border bg-surface p-6 sm:p-8" aria-labelledby="visa-medical-submission-heading">
  <h2 id="visa-medical-submission-heading" className="text-2xl font-semibold text-navy">검사받음 → 결과 전송 → 비자 결정은 다른 단계입니다</h2>
  <p className="mt-3 text-sm leading-7 text-muted">검사를 마칠 때 추가 검사가 남았는지, 결과 전송 예정일과 지연 시 연락처를 센터에 물으세요. eMedical Client의 Information Sheet에서 Department로 제출됐는지 확인하고, 아직 전송되지 않았다면 검사한 클리닉에 진행 상황을 문의할 수 있습니다. 이는 비자 승인 통지나 검사 원기록 전체를 받는 기능과는 다릅니다.</p>
  <p className="mt-4 text-sm leading-7 text-navy">검사 완료·결과 제출 표시만으로 항공편·퇴사·입주 날짜를 확정하지 말고, 실제 비자 결정문과 조건을 직접 확인하는 단계까지 이어가세요.</p>
  <blockquote className="mt-5 border-l-2 border-gold bg-white p-4 text-sm leading-7 text-navy">Could you confirm whether all examinations linked to my HAP ID have been submitted, whether anything remains outstanding, and who I should contact if submission is delayed?<span className="mt-2 block text-muted">제 검사 결과가 모두 제출됐는지, 남은 항목과 제출 지연 시 연락처를 확인해 주시겠어요?</span></blockquote>
  <p className="mt-3 text-xs leading-6 text-muted">일반 문의 문장입니다. 실제 HAP 번호는 본인의 공식 의료기관 문의 경로에서만 전달하고 이 공개 체크리스트에는 입력하지 마세요.</p>
  <a href="https://immi.homeaffairs.gov.au/help-support/tools/emedical/emedical-client" target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-11 items-center font-semibold text-navy underline decoration-gold underline-offset-4">Home Affairs eMedical 결과 제출 상태 안내 ↗</a>
  <p className="mt-3 text-xs leading-6 text-muted">2026-09-05에 첨부 사본 보관·검사 기한 통지·결과 제출 조회 경로를 대조했습니다. 개인별 비자 자격이나 모든 규정을 같은 날짜에 재검증한 것은 아닙니다.</p>
</section>
<section className="mt-10 grid gap-5 lg:grid-cols-[1fr_0.8fr]"><div className="rounded-2xl border border-border bg-white p-6"><h2 className="text-xl font-semibold text-navy">검사 당일 준비</h2><ul className="mt-4 space-y-2 text-sm leading-6 text-muted"><li>• Bupa·클리닉의 예약 확인서와 준비 안내를 우선 확인</li><li>• 원본 여권 등 지정된 신분증 준비—Bupa는 디지털·복사본을 받지 않는다고 안내</li><li>• Referral letter와 HAP ID를 안전하게 준비하되 공개 장소에 노출하지 않기</li><li>• 안경·렌즈, 복용약 목록이나 기존 의료 자료는 요청 안내에 따라 준비</li><li>• 임신 가능성, 이동 제한 또는 검사 관련 우려는 촬영·검사 전에 의료진에게 알리기</li></ul></div><div className="rounded-2xl border border-amber-300 bg-amber-50 p-6 text-sm leading-7 text-amber-950"><h2 className="font-semibold">중요한 이민·의료 안내</h2><p className="mt-1">이 페이지는 일반 정보이며 이민 또는 의료 자문이 아닙니다. 필요한 검사, 시기, 비자 자격과 제출 문서는 개인마다 다릅니다. ImmiAccount 요청과 해당 Subclass 페이지를 우선하고, 이민 도움을 받는다면 등록된 Migration Agent 또는 Australian legal practitioner인지 확인하세요.</p></div></section>
<section className="mt-8 rounded-2xl bg-navy p-6 text-white sm:flex sm:items-center sm:justify-between sm:gap-6"><div><p className="text-sm font-semibold text-gold">비자를 받았다면</p><h2 className="mt-2 text-xl font-semibold">호주 도착 후 첫 30일로 이어가세요</h2><p className="mt-2 text-sm leading-6 text-white/70">VEVO, 전화·교통, 은행, TFN과 의료·학생 절차를 시기별로 확인할 수 있습니다.</p></div><Link href="/arrival-checklist" className="mt-4 inline-flex min-h-11 shrink-0 items-center rounded-lg bg-gold px-4 text-sm font-semibold text-navy sm:mt-0">정착 체크리스트 &rarr;</Link></section>
</Container></main><Footer/></>}
