import Link from "next/link";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Container } from "@/components/ui/Container";
import { BreadcrumbJsonLd } from "@/components/seo/JsonLd";
import { InstallAppButton } from "@/components/pwa/InstallAppButton";
import { createPageMetadata } from "@/lib/site";

export const metadata = createPageMetadata({ title: "Aussie Compass 앱으로 사용하기", description: "별도 앱스토어 다운로드 없이 Aussie Compass를 iPhone과 Android 홈 화면에 추가하고 빠르게 이용하세요.", path: "/install" });

export default function InstallPage() {
  return <><BreadcrumbJsonLd items={[{ name: "홈", path: "/" }, { name: "앱으로 사용하기", path: "/install" }]} /><Header /><main className="py-12 sm:py-16"><Container><Link href="/" className="inline-flex min-h-11 items-center text-sm font-medium text-muted hover:text-navy">&larr; 홈으로 돌아가기</Link><section className="mt-7 overflow-hidden rounded-3xl bg-navy p-7 text-white sm:p-10"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-gold">Keep it within reach</p><h1 className="mt-3 max-w-3xl text-4xl font-semibold tracking-tight sm:text-5xl">필요할 때 바로 여는<br />나의 호주 생활 앱.</h1><p className="mt-5 max-w-2xl leading-7 text-white/70">앱스토어 가입이나 별도 계정 없이 현재 사이트를 휴대폰 홈 화면에 추가할 수 있습니다. 계산 기록과 체크리스트는 기존처럼 이 기기의 브라우저에만 저장됩니다.</p><InstallAppButton /></section><section id="manual-install" className="mt-12 scroll-mt-24"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-gold">Manual install</p><h2 className="mt-2 text-3xl font-semibold text-navy">기기별 설치 방법</h2><div className="mt-7 grid gap-6 lg:grid-cols-2"><article className="border-t-2 border-navy pt-5"><p className="font-mono text-xs text-gold">IPHONE · IPAD</p><h3 className="mt-2 text-xl font-semibold text-navy">Safari에서 홈 화면에 추가</h3><ol className="mt-4 space-y-3 text-sm leading-7 text-muted"><li><strong className="text-navy">01</strong> Safari에서 이 사이트를 엽니다.</li><li><strong className="text-navy">02</strong> 공유 버튼을 누릅니다.</li><li><strong className="text-navy">03</strong> ‘홈 화면에 추가’를 선택합니다.</li><li><strong className="text-navy">04</strong> ‘웹 앱으로 열기’를 켜고 추가합니다.</li></ol><a href="https://support.apple.com/guide/iphone/turn-a-website-into-an-app-iph42ab2f3a7/ios" target="_blank" rel="noreferrer" className="mt-5 inline-flex min-h-11 items-center text-sm font-semibold text-navy underline decoration-gold decoration-2 underline-offset-4">Apple 공식 설명 &nearr;</a></article><article className="border-t-2 border-navy pt-5"><p className="font-mono text-xs text-gold">ANDROID · CHROME</p><h3 className="mt-2 text-xl font-semibold text-navy">브라우저 메뉴에서 설치</h3><ol className="mt-4 space-y-3 text-sm leading-7 text-muted"><li><strong className="text-navy">01</strong> Chrome에서 이 사이트를 엽니다.</li><li><strong className="text-navy">02</strong> 오른쪽 위 메뉴를 누릅니다.</li><li><strong className="text-navy">03</strong> ‘앱 설치’ 또는 ‘홈 화면에 추가’를 선택합니다.</li><li><strong className="text-navy">04</strong> 표시되는 설치 안내를 확인합니다.</li></ol></article></div></section><section className="mt-12 grid gap-5 border-y border-border py-8 sm:grid-cols-3"><div><strong className="text-navy">로그인 불필요</strong><p className="mt-2 text-sm leading-6 text-muted">설치와 기본 도구 사용에 계정이 필요하지 않습니다.</p></div><div><strong className="text-navy">같은 웹주소</strong><p className="mt-2 text-sm leading-6 text-muted">공유받은 링크가 앱 안의 해당 도구로 바로 열립니다.</p></div><div><strong className="text-navy">언제든 삭제</strong><p className="mt-2 text-sm leading-6 text-muted">일반 앱처럼 홈 화면에서 제거할 수 있습니다.</p></div></section></Container></main><Footer /></>;
}
