import Link from "next/link";
import { ResumeJobAdVisitTracker } from "@/components/analytics/ResumeJobAdVisitTracker";
import { Footer } from "@/components/layout/Footer";
import { Header } from "@/components/layout/Header";
import { BreadcrumbJsonLd, WebApplicationJsonLd } from "@/components/seo/JsonLd";
import { ResumeJobAdChecker } from "@/components/tools/ResumeJobAdChecker";
import { Container } from "@/components/ui/Container";
import { createPageMetadata } from "@/lib/site";

export const metadata = createPageMetadata({
  title: "호주 이력서 공고 맞춤 점검기 | 무료 Job Ad 비교",
  description: "이력서와 호주 Job Ad를 서버 전송 없이 현재 화면에서 비교하고, 공고 표현 중 실제 경력 근거를 먼저 확인할 항목을 찾으세요.",
  path: "/resume-job-ad-checker",
});

export default function ResumeJobAdCheckerPage() {
  return <><ResumeJobAdVisitTracker /><WebApplicationJsonLd name="호주 이력서·Job Ad 공고 맞춤 근거 점검기" description="이력서와 호주 Job Ad를 서버 전송 없이 현재 화면에서 비교하고, 공고 표현 중 실제 경력 근거를 먼저 확인할 항목을 찾는 무료 웹 도구입니다." path="/resume-job-ad-checker" applicationCategory="BusinessApplication" featureList={["이력서와 Job Ad 텍스트를 현재 브라우저에서만 비교", "문구 일치와 실제 경력 근거 질문을 구분", "가상 예시와 원문 없는 근거 메모 제공"]} /><BreadcrumbJsonLd items={[{ name: "홈", path: "/" }, { name: "무료 도구", path: "/tools" }, { name: "이력서 공고 맞춤 점검기", path: "/resume-job-ad-checker" }]} /><Header /><main className="py-12 sm:py-16"><Container><Link href="/tools" className="inline-flex min-h-11 items-center text-sm font-medium text-muted hover:text-navy">&larr; 무료 도구 목록</Link><header className="mb-10 mt-5 max-w-4xl"><p className="text-sm font-semibold text-gold-ink">실제 공고가 생겼을 때</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-navy sm:text-5xl">호주 이력서·Job Ad<br /><span className="font-normal text-navy-light">공고 맞춤 근거 점검기</span></h1><p className="mt-5 max-w-3xl text-base leading-7 text-muted sm:text-lg">채용 가능성이나 ‘ATS 점수’를 만들어내지 않습니다. Job Ad에서 눈여겨볼 영문 표현 후보를 찾고, 현재 이력서에 같은 문구가 있는지 로컬에서 비교한 뒤 실제 경험 근거부터 확인하세요.</p><ul className="mt-6 grid gap-px border-y border-navy/15 bg-border text-sm sm:grid-cols-3"><li className="bg-white p-4"><strong className="block text-navy">서버 전송 없음</strong><span className="mt-1 block text-xs leading-5 text-muted">입력은 현재 화면에서만 처리해요.</span></li><li className="bg-white p-4"><strong className="block text-navy">점수·합격 예측 없음</strong><span className="mt-1 block text-xs leading-5 text-muted">문구 일치와 사실 근거를 구분해요.</span></li><li className="bg-white p-4"><strong className="block text-navy">무료 수정으로 연결</strong><span className="mt-1 block text-xs leading-5 text-muted">확인한 사실을 Builder에서 PDF로 정리해요.</span></li></ul></header><ResumeJobAdChecker /><section className="mt-12 border border-border bg-white p-6 sm:p-8" aria-labelledby="official-guidance-heading"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-gold">Official guidance</p><h2 id="official-guidance-heading" className="mt-2 text-xl font-semibold text-navy">왜 공고마다 확인해야 하나요?</h2><p className="mt-3 max-w-4xl text-sm leading-7 text-muted">Workforce Australia는 지원할 직무와 사업체를 조사하고, 공고가 찾는 기술·자격 중 실제로 가진 내용을 이력서 앞쪽에 두며 같은 키워드를 활용하라고 안내합니다. 제출 전에는 모든 정보가 사실인지 확인해야 해요.</p><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2"><a href="https://www.workforceaustralia.gov.au/individuals/coaching/job-applications/resumes" target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center font-semibold text-navy underline decoration-gold underline-offset-4">Workforce Australia · Write a resume ↗</a><a href="https://www.workforceaustralia.gov.au/individuals/coaching/job-applications/job-application-tips" target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center font-semibold text-navy underline decoration-gold underline-offset-4">Job application tips ↗</a></div></section></Container></main><Footer /></>;
}
